import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronRight, HeartPulse, LogOut, Share2, Shield, Stethoscope, TrendingUp, User } from "lucide-react";
import { api } from "../api.js";
import { useAuth } from "../auth.jsx";
import { useToast } from "../toast.jsx";
import { avatarGradient } from "../avatars.js";

function weekRangeLabel() {
  const now = new Date();
  const start = new Date(now.getTime() - 6 * 864e5);
  const fmt = (d) => d.toLocaleDateString(undefined, { month: "short", day: "numeric" });
  return `${fmt(start)} – ${fmt(now)}`;
}

function timeAgo(iso) {
  const then = new Date(iso + (iso.endsWith("Z") ? "" : "Z"));
  const mins = Math.round((Date.now() - then.getTime()) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.round(hrs / 24)}d ago`;
}

export default function Profile() {
  const { user, logout } = useAuth();
  const navigate = useNavigate();
  const toast = useToast();
  const [checks, setChecks] = useState(null);
  const [reminderCount, setReminderCount] = useState(null);
  const [doctors, setDoctors] = useState([]);

  useEffect(() => {
    api.history(100).then(setChecks).catch(() => setChecks([]));
    api.listReminders().then((r) => setReminderCount(r.length)).catch(() => setReminderCount(0));
    api.listDoctors().then(setDoctors).catch(() => setDoctors([]));
  }, []);

  const myDoctor = doctors.find((d) => d.id === user?.doctor_id);

  // Weekly report: symptom checks this week vs last week.
  const now = Date.now();
  const inRange = (iso, from, to) => {
    const t = new Date(iso + (iso.endsWith("Z") ? "" : "Z")).getTime();
    return t >= from && t < to;
  };
  const thisWeek = (checks ?? []).filter((c) => inRange(c.created_at, now - 7 * 864e5, now + 864e5)).length;
  const lastWeek = (checks ?? []).filter((c) => inRange(c.created_at, now - 14 * 864e5, now - 7 * 864e5)).length;
  const delta = thisWeek - lastWeek;

  async function shareData() {
    try {
      const recent = (checks ?? []).slice(0, 10);
      const text = [
        `HealthNav summary — ${user.name}`,
        user.age ? `Age: ${user.age}` : null,
        user.conditions ? `Conditions: ${user.conditions}` : null,
        "",
        "Recent symptom checks:",
        ...(recent.length ? recent.map((c) => `• ${c.symptom_text} → ${c.urgency} (${c.created_at.slice(0, 10)})`) : ["• none yet"]),
        "",
        "Generated by HealthNav — guidance, not diagnosis.",
      ].filter((l) => l !== null).join("\n");
      if (navigator.share) await navigator.share({ title: "HealthNav summary", text });
      else { await navigator.clipboard.writeText(text); toast("Summary copied to clipboard."); }
    } catch (err) {
      if (err?.name !== "AbortError") toast("Couldn't share — " + (err.message ?? ""), "error");
    }
  }

  return (
    <section>
      {/* Profile header */}
      <div className="card mypage-header">
        <div className="avatar-lg" style={{ background: avatarGradient(user?.avatar ?? "mint") }}>
          <User size={34} color="#ffffff" />
        </div>
        <div className="mypage-name">{user?.name}</div>
        <button className="edit-pill" onClick={() => navigate("/profile/edit")}>Edit</button>
      </div>

      {/* Health data sharing */}
      <button className="card share-card" onClick={shareData}>
        <div className="row" style={{ width: "100%" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.7rem" }}>
            <span className="settings-icon"><Share2 size={18} /></span>
            <strong>Health data sharing</strong>
          </div>
          <ChevronRight size={18} color="var(--muted)" />
        </div>
        <p className="muted" style={{ margin: "0.6rem 0 0", fontSize: "0.85rem" }}>
          Securely share your stored health summary with a clinician (with consent).
        </p>
      </button>

      {/* Weekly report */}
      <div className="card">
        <h2 style={{ marginBottom: "0.15rem" }}>Weekly report</h2>
        <div className="med-dose" style={{ marginBottom: "0.9rem" }}>{weekRangeLabel()}</div>
        <div className="report-grid">
          <div className="report-stat">
            <div className="report-label"><TrendingUp size={15} color="var(--self_care)" /> Symptom checks</div>
            <div className="muted" style={{ fontSize: "0.78rem" }}>Previous week {lastWeek}</div>
            {delta !== 0 && (
              <span className={`delta ${delta > 0 ? "up" : "down"}`}>{delta > 0 ? "▲" : "▼"} {Math.abs(delta)}</span>
            )}
            <div className="report-value">{thisWeek}</div>
          </div>
          <div className="report-divider" />
          <div className="report-stat">
            <div className="report-label"><HeartPulse size={15} color="var(--self_care)" /> Active reminders</div>
            <div className="muted" style={{ fontSize: "0.78rem" }}>Medications tracked</div>
            <div className="report-value">{reminderCount ?? "—"}</div>
          </div>
        </div>
      </div>

      {/* Quick links */}
      <div className="card" style={{ padding: 0, overflow: "hidden" }}>
        <button className="row settings-row" onClick={() => navigate("/profile/edit")} style={{ borderBottom: "1px solid var(--line)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
            <span className="settings-icon"><Stethoscope size={18} /></span>
            <div style={{ textAlign: "left" }}>
              <div className="med-name" style={{ fontSize: "0.92rem" }}>Your doctor</div>
              <div className="med-dose">{myDoctor ? `Dr. ${myDoctor.name}` : "None selected — tap to choose"}</div>
            </div>
          </div>
          <ChevronRight size={18} color="var(--muted)" />
        </button>
        <button className="row settings-row" onClick={() => navigate("/history")} style={{ borderBottom: "1px solid var(--line)" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
            <span className="settings-icon"><HeartPulse size={18} /></span>
            <div style={{ textAlign: "left" }}>
              <div className="med-name" style={{ fontSize: "0.92rem" }}>Health history</div>
              <div className="med-dose">Past symptom checks & guidance</div>
            </div>
          </div>
          <ChevronRight size={18} color="var(--muted)" />
        </button>
        <div className="row settings-row" style={{ cursor: "default" }}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
            <span className="settings-icon"><Shield size={18} /></span>
            <div style={{ textAlign: "left" }}>
              <div className="med-name" style={{ fontSize: "0.92rem" }}>Privacy & safety</div>
              <div className="med-dose">Your data stays in your account only</div>
            </div>
          </div>
        </div>
      </div>

      <button className="btn btn-outline" onClick={logout}>
        <LogOut size={18} style={{ marginRight: "0.4rem", verticalAlign: "-3px" }} />
        Sign out
      </button>
      <p className="disclaimer" style={{ textAlign: "center" }}>Educational student project — not a medical device.</p>
    </section>
  );
}
