import { useState } from "react";
import { useNavigate } from "react-router-dom";
import { ChevronRight, FileText, HeartPulse, LogOut, Shield, User } from "lucide-react";
import { api } from "../api.js";
import { useAuth } from "../auth.jsx";

export default function Profile() {
  const { user, logout, setUser } = useAuth();
  const navigate = useNavigate();
  const [open, setOpen] = useState(null); // "basics" | "privacy" | null
  const [note, setNote] = useState(null);
  const [form, setForm] = useState({
    name: user?.name ?? "",
    age: user?.age ?? "",
    sex: user?.sex ?? "",
    conditions: user?.conditions ?? "",
  });
  const [saving, setSaving] = useState(false);

  const set = (k) => (e) => setForm({ ...form, [k]: e.target.value });
  const toggle = (key) => setOpen((o) => (o === key ? null : key));

  async function saveBasics(e) {
    e.preventDefault();
    setSaving(true);
    setNote(null);
    try {
      const updated = await api.updateMe({
        name: form.name,
        age: form.age ? Number(form.age) : null,
        sex: form.sex || null,
        conditions: form.conditions.trim() || null,
      });
      setUser(updated);
      setNote("Profile saved.");
      setOpen(null);
    } catch (err) {
      setNote(err.message);
    } finally {
      setSaving(false);
    }
  }

  async function shareWithClinician() {
    setNote(null);
    try {
      const checks = await api.history(10);
      const lines = [
        `HealthNav summary — ${user.name}`,
        user.age ? `Age: ${user.age}` : null,
        user.sex ? `Sex: ${user.sex}` : null,
        user.conditions ? `Conditions: ${user.conditions}` : null,
        "",
        "Recent symptom checks:",
        ...(checks.length
          ? checks.map((c) => `• ${c.symptom_text} → ${c.urgency} (${c.created_at.slice(0, 10)})`)
          : ["• none yet"]),
        "",
        "Generated by HealthNav — guidance, not diagnosis.",
      ].filter((l) => l !== null);
      const text = lines.join("\n");

      if (navigator.share) {
        await navigator.share({ title: "HealthNav summary", text });
        setNote("Summary shared.");
      } else {
        await navigator.clipboard.writeText(text);
        setNote("Summary copied to clipboard.");
      }
    } catch (err) {
      if (err?.name !== "AbortError") setNote("Couldn't share — " + (err.message ?? ""));
    }
  }

  const ITEMS = [
    { key: "basics", Icon: User, title: "Profile basics", sub: "Name, age, conditions", onClick: () => toggle("basics") },
    { key: "history", Icon: HeartPulse, title: "Health history", sub: "Past symptom checks & guidance", onClick: () => navigate("/history") },
    { key: "share", Icon: FileText, title: "Share with clinician", sub: "One-tap summary (with consent)", onClick: shareWithClinician },
    { key: "privacy", Icon: Shield, title: "Privacy & safety", sub: "How your data is handled", onClick: () => toggle("privacy") },
  ];

  return (
    <section>
      <h2 className="page-title">Your profile</h2>
      <p className="page-sub">A private, persistent record of your health.</p>

      <div className="card" style={{ display: "flex", alignItems: "center", gap: "0.9rem" }}>
        <span className="avatar">{user?.name?.[0]?.toUpperCase() ?? "U"}</span>
        <div>
          <div className="med-name">{user?.name}</div>
          <div className="med-dose">{user?.email}</div>
        </div>
      </div>

      {note && <div className="card note">{note}</div>}

      <div className="card" style={{ padding: 0, overflow: "hidden" }}>
        {ITEMS.map(({ key, Icon, title, sub, onClick }, i) => (
          <div key={key} style={{ borderBottom: i < ITEMS.length - 1 ? "1px solid var(--line)" : "none" }}>
            <button className="row settings-row" onClick={onClick}>
              <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
                <span className="settings-icon"><Icon size={18} /></span>
                <div style={{ textAlign: "left" }}>
                  <div className="med-name" style={{ fontSize: "0.92rem" }}>{title}</div>
                  <div className="med-dose">{sub}</div>
                </div>
              </div>
              <ChevronRight size={18} color="var(--muted)" style={{
                transform: open === key ? "rotate(90deg)" : "none", transition: "transform 0.15s",
              }} />
            </button>

            {key === "basics" && open === "basics" && (
              <form className="expander form-grid" onSubmit={saveBasics}>
                <input placeholder="Full name" value={form.name} onChange={set("name")} required />
                <div className="field-row">
                  <input type="number" min="0" max="120" placeholder="Age" value={form.age} onChange={set("age")} />
                  <select className="field" value={form.sex} onChange={set("sex")}>
                    <option value="">Sex —</option>
                    <option value="female">Female</option>
                    <option value="male">Male</option>
                    <option value="other">Other</option>
                  </select>
                </div>
                <textarea rows={2} placeholder="Existing conditions" value={form.conditions} onChange={set("conditions")} />
                <button className="btn" type="submit" disabled={saving}>
                  {saving ? "Saving…" : "Save changes"}
                </button>
              </form>
            )}

            {key === "privacy" && open === "privacy" && (
              <div className="expander">
                <p className="muted" style={{ margin: 0, lineHeight: 1.5 }}>
                  Your profile and history are stored in HealthNav's database and tied to your
                  account only. Guidance is generated under human oversight and is never a
                  diagnosis. Nothing is shared with anyone unless you choose to share a summary.
                  Sign out on a shared device to end your session.
                </p>
              </div>
            )}
          </div>
        ))}
      </div>

      <button className="btn btn-outline" onClick={logout}>
        <LogOut size={18} style={{ marginRight: "0.4rem", verticalAlign: "-3px" }} />
        Sign out
      </button>

      <p className="disclaimer" style={{ textAlign: "center" }}>
        Educational student project — not a medical device.
      </p>
    </section>
  );
}
