import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { Activity, Edit2, FileText, LogOut, Shield } from "lucide-react";
import { api } from "../api.js";
import { useAuth } from "../auth.jsx";

function timeAgo(iso) {
  const then = new Date(iso + (iso.endsWith("Z") ? "" : "Z"));
  const mins = Math.round((Date.now() - then.getTime()) / 60000);
  if (mins < 1) return "just now";
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.round(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  return `${Math.round(hrs / 24)}d ago`;
}

export default function Profile() {
  const { user, logout, setUser } = useAuth();
  const navigate = useNavigate();
  const [editing, setEditing] = useState(false);
  const [showPrivacy, setShowPrivacy] = useState(false);
  const [note, setNote] = useState(null);
  const [checks, setChecks] = useState(null);
  const [form, setForm] = useState({
    name: user?.name ?? "",
    age: user?.age ?? "",
    sex: user?.sex ?? "",
    conditions: user?.conditions ?? "",
  });
  const [saving, setSaving] = useState(false);

  useEffect(() => {
    api.history(5).then(setChecks).catch(() => setChecks([]));
  }, []);

  const set = (k) => (e) => setForm({ ...form, [k]: e.target.value });

  async function saveBasics(e) {
    e.preventDefault();
    setSaving(true);
    setNote(null);
    try {
      const updated = await api.updateMe({
        name: form.name,
        age: form.age ? Number(form.age) : null,
        sex: form.sex || null,
        conditions: form.conditions.trim() || null,
      });
      setUser(updated);
      setNote("Profile saved.");
      setEditing(false);
    } catch (err) {
      setNote(err.message);
    } finally {
      setSaving(false);
    }
  }

  async function shareWithClinician() {
    setNote(null);
    try {
      const recent = await api.history(10);
      const lines = [
        `HealthNav summary — ${user.name}`,
        user.age ? `Age: ${user.age}` : null,
        user.sex ? `Sex: ${user.sex}` : null,
        user.conditions ? `Conditions: ${user.conditions}` : null,
        "",
        "Recent symptom checks:",
        ...(recent.length
          ? recent.map((c) => `• ${c.symptom_text} → ${c.urgency} (${c.created_at.slice(0, 10)})`)
          : ["• none yet"]),
        "",
        "Generated by HealthNav — guidance, not diagnosis.",
      ].filter((l) => l !== null);
      const text = lines.join("\n");

      if (navigator.share) {
        await navigator.share({ title: "HealthNav summary", text });
        setNote("Summary shared.");
      } else {
        await navigator.clipboard.writeText(text);
        setNote("Summary copied to clipboard.");
      }
    } catch (err) {
      if (err?.name !== "AbortError") setNote("Couldn't share — " + (err.message ?? ""));
    }
  }

  return (
    <section>
      <h2 className="page-title">Your profile</h2>
      <p className="page-sub">A private, persistent record of your health.</p>

      <div className="card" style={{ display: "flex", alignItems: "center", gap: "0.9rem" }}>
        <span className="avatar">{user?.name?.[0]?.toUpperCase() ?? "U"}</span>
        <div>
          <div className="med-name">{user?.name}</div>
          <div className="med-dose">{user?.email}</div>
        </div>
      </div>

      {note && <div className="card note">{note}</div>}

      <div className="card" style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start" }}>
        {editing ? (
          <form className="form-grid" style={{ width: "100%" }} onSubmit={saveBasics}>
            <input placeholder="Full name" value={form.name} onChange={set("name")} required />
            <div className="field-row">
              <input type="number" min="0" max="120" placeholder="Age" value={form.age} onChange={set("age")} />
              <select className="field" value={form.sex} onChange={set("sex")}>
                <option value="">Sex —</option>
                <option value="female">Female</option>
                <option value="male">Male</option>
                <option value="other">Other</option>
              </select>
            </div>
            <textarea rows={2} placeholder="Existing conditions" value={form.conditions} onChange={set("conditions")} />
            <div style={{ display: "flex", gap: "0.6rem" }}>
              <button className="btn" type="submit" disabled={saving}>
                {saving ? "Saving…" : "Save changes"}
              </button>
              <button className="btn btn-outline" type="button" onClick={() => setEditing(false)}>
                Cancel
              </button>
            </div>
          </form>
        ) : (
          <>
            <dl className="profile-summary" style={{ margin: 0, flex: 1 }}>
              <div className="profile-row"><dt>Name</dt><dd>{user?.name || "—"}</dd></div>
              <div className="profile-row"><dt>Age</dt><dd>{user?.age ?? "—"}</dd></div>
              <div className="profile-row"><dt>Sex</dt><dd>{user?.sex || "—"}</dd></div>
              <div className="profile-row"><dt>Existing conditions</dt><dd>{user?.conditions || "None on file"}</dd></div>
            </dl>
            <button className="icon-btn" onClick={() => setEditing(true)} aria-label="Edit profile">
              <Edit2 size={18} />
            </button>
          </>
        )}
      </div>

      <div className="section-head">
        <h2>Past symptoms</h2>
        <button className="link-more" onClick={() => navigate("/history")}>See all</button>
      </div>
      {checks === null ? (
        <div className="card skeleton-row" />
      ) : checks.length === 0 ? (
        <div className="empty">No symptom checks yet.</div>
      ) : (
        checks.map((c) => (
          <div className="card activity-row" key={c.id}>
            <span className="mini-icon"><Activity size={16} /></span>
            <div style={{ flex: 1, minWidth: 0 }}>
              <div className="activity-text">{c.symptom_text}</div>
              <div className="med-dose">{timeAgo(c.created_at)}</div>
            </div>
          </div>
        ))
      )}

      <div className="card" style={{ padding: 0 }}>
        <button className="row settings-row" onClick={shareWithClinician}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
            <span className="settings-icon"><FileText size={18} /></span>
            <div style={{ textAlign: "left" }}>
              <div className="med-name" style={{ fontSize: "0.92rem" }}>Share with clinician</div>
              <div className="med-dose">One-tap summary (with consent)</div>
            </div>
          </div>
        </button>
      </div>

      <div className="card" style={{ padding: 0 }}>
        <button className="row settings-row" onClick={() => setShowPrivacy((v) => !v)}>
          <div style={{ display: "flex", alignItems: "center", gap: "0.85rem" }}>
            <span className="settings-icon"><Shield size={18} /></span>
            <div style={{ textAlign: "left" }}>
              <div className="med-name" style={{ fontSize: "0.92rem" }}>Privacy & safety</div>
              <div className="med-dose">How your data is handled</div>
            </div>
          </div>
        </button>
        {showPrivacy && (
          <div className="expander">
            <p className="muted" style={{ margin: 0, lineHeight: 1.5 }}>
              Your profile and history are stored in HealthNav's database and tied to your
              account only. Guidance is generated under human oversight and is never a
              diagnosis. Nothing is shared with anyone unless you choose to share a summary.
              Sign out on a shared device to end your session.
            </p>
          </div>
        )}
      </div>

      <button className="btn btn-outline" onClick={logout}>
        <LogOut size={18} style={{ marginRight: "0.4rem", verticalAlign: "-3px" }} />
        Sign out
      </button>

      <p className="disclaimer" style={{ textAlign: "center" }}>
        Educational student project — not a medical device.
      </p>
    </section>
  );
}
